version: '3.8'

services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - D:/Program/Ollama/models:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama
    command: serve

volumes:
  ollama_data: 