name: Deploy RAG System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Build and run with Docker Compose
      run: |
        docker-compose up -d
        # Wait for services to be healthy
        timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000/health)" != "200" ]]; do sleep 5; done'
        
    - name: Test API
      run: |
        curl -X POST http://localhost:8000/query \
          -H "Content-Type: application/json" \
          -d '{"query": "test query"}'
          
    - name: Check service logs
      if: failure()
      run: |
        docker-compose logs
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist 