name: Deploy RAG System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.mcp.txt
        
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        # Set Ollama to use the GitHub Actions workspace
        export OLLAMA_MODELS=$GITHUB_WORKSPACE/ollama_models
        mkdir -p $OLLAMA_MODELS
        # Add Ollama to PATH
        echo "$HOME/.ollama" >> $GITHUB_PATH
        
    - name: Pull Ollama model
      run: |
        ollama pull phi:2.7b
        
    - name: Process documents
      run: |
        python -m src.cli process
        
    - name: Start MCP server
      run: |
        python -m src.mcp_server &
        
    - name: Wait for server
      run: |
        sleep 10
        
    - name: Test API
      run: |
        curl -X POST http://localhost:8000/query \
          -H "Content-Type: application/json" \
          -d '{"query": "test query"}'
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist 